manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/y3sen
  projects:
    - name: zmk-pete 
      remote: zmkfirmware
      revision: main 
      import: app/west.yml
  self:
    path: config
